# Generated by Django 4.2.3 on 2024-06-09 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_eventtype_remove_event_name_event_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventtype'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
