# Generated by Django 4.2.3 on 2024-06-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_itemtype_remove_event_description_remove_event_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='naam',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='naam',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
