# Generated by Django 4.2.3 on 2024-06-10 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_eventtype_type_alter_item_naam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='naam',
            new_name='type',
        ),
    ]
