# Generated by Django 4.2.3 on 2024-06-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_naam_itemtype_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='calenderid',
            new_name='calendarid',
        ),
    ]
